### Variáveis
@url=http://localhost:3001
@contato_id=27bc892d-a13a-4a22-a4b4-89a141558ceb


### GET
GET {{url}}/contatos

### GET por ID
GET {{url}}/contatos/{{contato_id}}


### POST
POST {{url}}/contatos
Content-Type: application/json

{
    "nome":"Bernardo",
    "email": "bernardo@gmail.com",
    "telefone": "44123451234"
}

### PUT
PUT {{url}}/contatos/{{contato_id}}
Content-Type: application/json

{    
    "nome":"João Silva",
    "email": "joao-silva@gmail.com",
    "telefone": "44123451234"
}

### DELETE
DELETE {{url}}/contatos/{{contato_id}}

